### ISSUE TITLE
Failed to initialize chi with latest version of clickhouse-server when reading credentials from Secret

### ISSUE THREAD

**Issue by a-dot** [Altinity/clickhouse-operator#1128]
Hi, I'm trying to instantiate a CHI with the latest version of clickhouse-server (23.2) and the latest version of clickhouse-operator (0.20.3). 
The username/password for clickhouse-operator are retrieved through a Secret. However, since you removed the default <password_sha256_hex> entry in the users config, the chi refuses to start with this error:

```
<Error> Application: Code: 36: DB::Exception: Either 'password' or 'password_sha256_hex' or 'password_double_sha1_hex' or 'no_password' or 'ldap' or 'kerberos' or 'ssl_certificates' must be specified for user clickhouse_operator.: while parsing user 'clickhouse_operator' in users configuration file: while loading configuration file /etc/clickhouse-server/users.xml'. (BAD_ARGUMENTS)
```

**Comment by alex-zaitsev** [comment]
Hi @a-dot , user/pass is read from Secret and then propagated to users.xml. Could you show your 'chi-{chi}-common-usersd' configmap (chi is a name of ClickHouse installation). Ther should be 'chop-generated-users.xml' section with a proper password.

You can also specify it explicitly in operator configuration, if you do not want to use a secret.

**Comment by a-dot** [comment]
As you can see from the configmap it's missing a "password" tag.

I installed the operator by doing this:
`CH_USERNAME_SECRET_PLAIN=clickhouse-operator CH_PASSWORD_SECRET_PLAIN=password OPERATOR_NAMESPACE=clickhouse-operator WATCH_NAMESPACES=myNS ./cat-clickhouse-operator-install-yaml.sh | kubectl -n clickhouse-operator apply -f -`

```
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: clickhouse-operator
    clickhouse.altinity.com/chop: 0.20.3
  name: etc-clickhouse-operator-usersd-file
  namespace: clickhouse-operator
data:
  01-clickhouse-user.xml: |
	<!-- IMPORTANT -->
	<!-- This file is auto-generated -->
	<!-- Do not edit this file - all changes would be lost -->
	<!-- Edit appropriate template in the following folder: -->
	<!-- deploy/builder/templates-config -->
	<!-- IMPORTANT -->
	<!--
	#
	# Template parameters available:
	#
	-->
	<yandex>
    	<users>
        	<clickhouse_operator>
            	<networks>
                	<ip>127.0.0.1</ip>
            	</networks>
            	<profile>clickhouse_operator</profile>
            	<quota>default</quota>
        	</clickhouse_operator>
    	</users>
    	<profiles>
        	<clickhouse_operator>
            	<log_queries>0</log_queries>
            	<skip_unavailable_shards>1</skip_unavailable_shards>
            	<http_connection_timeout>10</http_connection_timeout>
            	<max_concurrent_queries_for_all_users>0</max_concurrent_queries_for_all_users>
            	<os_thread_priority>0</os_thread_priority>
        	</clickhouse_operator>
    	</profiles>
	</yandex>
  02-clickhouse-default-profile.xml: |
	<!-- IMPORTANT -->
	<!-- This file is auto-generated -->
	<!-- Do not edit this file - all changes would be lost -->
	<!-- Edit appropriate template in the following folder: -->
	<!-- deploy/builder/templates-config -->
	<!-- IMPORTANT -->
	<yandex>
  	<profiles>
    	<default>
      	<os_thread_priority>2</os_thread_priority>
      	<log_queries>1</log_queries>
      	<connect_timeout_with_failover_ms>1000</connect_timeout_with_failover_ms>
      	<distributed_aggregation_memory_efficient>1</distributed_aggregation_memory_efficient>
      	<parallel_view_processing>1</parallel_view_processing>
      	<do_not_merge_across_partitions_select_final>1</do_not_merge_across_partitions_select_final>
      	<load_balancing>nearest_hostname</load_balancing>
    	</default>
  	</profiles>
	</yandex>
  03-database-ordinary.xml: |
	<!-- IMPORTANT -->
	<!-- This file is auto-generated -->
	<!-- Do not edit this file - all changes would be lost -->
	<!-- Edit appropriate template in the following folder: -->
	<!-- deploy/builder/templates-config -->
	<!-- IMPORTANT -->
	<!--  Remove it for ClickHouse versions before 20.4 -->
	<yandex>
    	<profiles>
        	<default>
            	<default_database_engine>Ordinary</default_database_engine>
        	</default>
    	</profiles>
	</yandex>
```

**Comment by Slach** [comment]
Look to `etc-clickhouse-operator-files` configmap
Look to `config.yml` section
```
clickhouse:
  access:
    secret:
```  
Is your generated ConfigMap containing `namespace` and `name` in secret section? is namespace empty?
do you have secret with name `clickhouse-operator` in `clickhouse-operator` namespace?

https://github.com/Altinity/clickhouse-operator/blob/master/docs/quick_start.md#clickhouse-operator-installation

Recommended way to install clickhouse-operator for your use case
```
curl -s https://raw.githubusercontent.com/Altinity/clickhouse-operator/master/deploy/operator-web-installer/clickhouse-operator-install.sh | CH_USERNAME_SECRET_PLAIN=clickhouse-operator CH_PASSWORD_SECRET_PLAIN=password OPERATOR_NAMESPACE=clickhouse-operator WATCH_NAMESPACES=myNS OPERATOR_NAMESPACE=clickhouse-operator bash
```

**Comment by alex-zaitsev** [comment]
@a-dot , password is not going to be in 'etc-clickhouse-operator-usersd-file'. This is a static configmap. 

Secret reference is in 'etc-clickhouse-operator-files'.config.yml, and it is resolved to ClickHouse configuration in 'chi-{chi}-common-usersd'.chop-generated-users.xml

**Comment by a-dot** [comment]
@Slach , the namespace entry in clickhouse/access/secret was blank but the name entry was not. I tried editing the namespace from my generated yaml before applying it and adding the namespace and reapplying that file. That had no effect, I'm still getting the same error in clickhouse-server when instantiating a new CHI.

I also tried your command, passing the same variables and the result is the same, same error in clickhouse-server.

I'm not sure that's the problem as the username/password are getting picked up (confirmed from the clickhouse-operator logs and from the xml in the running pod).

The problem is that clickhouse_operator user (with an underscore) which is hardcoded in 01-clickhouse-user.xml contains no password and the server is giving an error and exiting.

**Comment by alex-zaitsev** [comment]
@a-dot 

```01-clickhouse-user.xml``` does not matter at all. The password hash is provided in  ```users.d/chop-generated-users.xml```, and ClickHouse then merges everything together. Here is an example of a simplest installation:

```
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: test-001
spec:
  configuration:
    clusters:
      - name: single
```

Once applied, here is a configmap (cut):
```
kubectl get cm chi-test-001-common-usersd -n test -o yaml

....
  chop-generated-users.xml: |
    <yandex>
        <users>
            <clickhouse_operator>
                <networks>
                    <ip>172.17.0.6</ip>
                </networks>
                <password remove="1"></password>
                <password_sha256_hex>716b36073a90c6fe1d445ac1af85f4777c5b7a155cea359961826a030513e448</password_sha256_hex>
            </clickhouse_operator>
....
```

**Comment by a-dot** [comment]
I don't think you understand what I'm saying... I'm not installing with the clickhouse_operator user. What you're saying would be true if it was the case but because I'm specifying a different user that clickhouse_operator user is created with no password (and another one is created for the custom user I'm using). However because the hardcoded user clickhouse_operator is created without a password, the server refuses to start.

Hope that makes more sense?

**Comment by alex-zaitsev** [comment]
Now I've got it, thanks! You've changed the user name. Maybe we need to disallow doing that, and allow changing password only. Otherwise, we can not control the profile and some other other things.

**Comment by a-dot** [comment]
I think you'd have to, yes. 
Remove the ability to specify a username if you don't support that change. Otherwise, clickhouse-server won't start when a different username is specified through CH_USERNAME_SECRET_PLAIN or CH_USERNAME_PLAIN.

**Comment by alex-zaitsev** [comment]
Let's see if it fixes that: https://github.com/Altinity/clickhouse-operator/commit/536781c234b5c9834b7ccca9a044768869586db2

**Comment by alex-zaitsev** [comment]
Yes, we need a profile to be there. It will be used for whatever user is configured in configuration.

**Comment by a-dot** [comment]
> Yes, we need a profile to be there. It will be used for whatever user is configured in configuration.

Right, the profile needs to exist, but if it's specified as
```
<profiles>
  <clickhouse_operator>
    [...]
  </clickhouse_operator>
</profiles>
```

It won't work with a custom username

**Comment by a-dot** [comment]
Nevermind... I misread it.. that's the profile's name!

**Comment by alex-zaitsev** [comment]
Fixed in 0.21.0.
